name: 📈 Generate Tagging Coverage Report

on:
  workflow_dispatch:
    inputs:
      billing_period:
        description: "Billing period in format YYYY-MM (e.g., 2025-01)"
        required: true
        type: string
      business_unit:
        description: "Select a business unit"
        required: true
        type: choice
        options:
          - HMPPS
          - LAA
          - Central Digital
          - Technology Services
          - OPG
          - HMCTS
          - YJB
          - CICA
          - OCTO

permissions:
  id-token: write
  contents: write

jobs:
  generate-tagging-coverage-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.12"
          cache: "pipenv"
      - name: Install Pipenv
        run: |
          pip install pipenv
          pipenv install
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@e977f476bf97137dd509f98c23d8d100c08a6862 # v4.0.2
        with:
          role-to-assume: ${{secrets.AWS_COAT_GITHUB_ACTIONS_ROLE_ARN}}
          aws-region: eu-west-2
      - name: Run Python script
        run: |
            pipenv run python3 -m bin.tagging_coverage_report \
            --billing_period "${{ github.event.inputs.billing_period }}" \
            --business_unit "${{ github.event.inputs.business_unit }}"
        env:
          GH_TOKEN: ${{ secrets.ENTERPRISE_BILLING_TOKEN_FROM_TONY }}
          ADMIN_SLACK_TOKEN: ${{ secrets.ADMIN_SLACK_TOKEN }}
      - name: Report failure to Slack
        if: failure()
        uses: slackapi/slack-github-action@45a88b9581bfab2566dc881e2cd66d334e621e2c # v3.0.3
        with:
          payload: |
            {
              "text": "❌ Failed to run Generate Tagging Coverage Report job",
              "attachments": [
                {
                  "color": "danger",
                  "title": "Failed to run Generate Tagging Coverage Report job",
                  "fields": [
                    {
                      "title": "Status",
                      "value": "${{ job.status }}",
                      "short": true
                    },
                    {
                      "title": "Repository",
                      "value": "${{ github.repository }}",
                      "short": true
                    },
                    {
                      "title": "Workflow",
                      "value": "${{ github.workflow }}",
                      "short": true
                    },
                    {
                      "title": "Run",
                      "value": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                      "short": false
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
